"""Unit tests for ``ltagent.netlist`` (Phase 2).

These tests cover the acceptance criteria from plan section 21 (Phase 2):

- Voltage divider and RC examples generate valid-looking ``.cir`` files.
- Snapshot tests check required lines (header, components, analyses,
  measurements, ``.end``).
- Unsafe directives are rejected with a structured error code.
- The IR's ``.end`` is not emitted as a duplicate.

Tests do not require LTspice, Wine, or the network.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from ltagent import __version__
from ltagent.ir import (
    Analysis,
    AnalysisKind,
    CircuitIR,
    Component,
    ComponentKind,
    load_ir,
)
from ltagent.netlist import (
    DIRECTIVE_ALLOWLIST,
    GENERATOR_NAME,
    NetlistError,
    NetlistResult,
    render_netlist,
    write_netlist,
)
from tests._testdata import EXAMPLES, EXAMPLES_DIR

# --- helpers --------------------------------------------------------------


def _strip_blank_lines(text: str) -> list[str]:
    return [line for line in text.splitlines() if line.strip()]


def _render_lines(ir: CircuitIR) -> list[str]:
    return _strip_blank_lines(render_netlist(ir).text)


# --- example snapshot tests ----------------------------------------------


@pytest.mark.parametrize("example_name", EXAMPLES)
def test_example_netlist_has_required_sections(example_name: str) -> None:
    """All three MVP examples must produce a netlist with header,
    components, at least one analysis, optional measurements, and ``.end``."""
    ir = load_ir(EXAMPLES_DIR / f"{example_name}.ir.json")
    result = render_netlist(ir)
    lines = _render_lines(ir)

    # Header.
    assert lines[0].startswith(f"* Generated by {GENERATOR_NAME}")
    assert f"{__version__}" in lines[0]
    assert f"* Project: {ir.name}" in lines[1]
    assert f"* Topology: {ir.topology}" in lines[2]

    # Component lines (one per IR component, in IR order). A component
    # line starts with an identifier (letter, not `*` or `.`) followed by
    # nodes and a value.
    component_line_ids = [
        line.split()[0]
        for line in lines
        if line and not line.startswith(".") and not line.startswith("*")
    ]
    assert component_line_ids == [c.id for c in ir.components]

    # .end at the end.
    assert lines[-1] == ".end"
    # .end must appear exactly once.
    assert sum(1 for line in lines if line.strip() == ".end") == 1

    # At least one analysis directive.
    analysis_lines = [line for line in lines if line.startswith(".")]
    assert any(line.startswith((".tran", ".op", ".dc", ".ac")) for line in analysis_lines)
    assert result.analysis_count >= 1

    # Counters.
    assert result.component_count == len(ir.components)
    assert result.measurement_count == len(ir.measurements)


def test_voltage_divider_netlist_matches_plan_reference() -> None:
    """Plan section 11.2 lists the RC low-pass output. Voltage divider is
    also in the MVP and must follow the same shape."""
    ir = load_ir(EXAMPLES_DIR / "voltage_divider.ir.json")
    text = render_netlist(ir).text
    lines = _strip_blank_lines(text)
    assert lines[0] == f"* Generated by {GENERATOR_NAME} {__version__}"
    assert lines[1] == "* Project: voltage_divider_12v_to_5v"
    assert lines[2] == "* Topology: voltage_divider"
    assert "Vin in 0 DC 12" in lines
    assert "R1 in out 1.4k" in lines
    assert "R2 out 0 1k" in lines
    assert ".op" in lines
    assert ".meas op VOUT V(out)" in lines
    assert lines[-1] == ".end"


def test_rc_lowpass_netlist_matches_plan_reference() -> None:
    """Plan section 11.2 publishes the exact RC low-pass netlist shape."""
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    text = render_netlist(ir).text
    lines = _strip_blank_lines(text)
    assert lines[0] == f"* Generated by {GENERATOR_NAME} {__version__}"
    assert lines[1] == "* Project: rc_lowpass_1khz"
    assert lines[2] == "* Topology: rc_lowpass"
    # Component order must match IR order.
    assert "Vin in 0 SINE(0 1 1k)" in lines
    assert "R1 in out 1.59k" in lines
    assert "C1 out 0 100n" in lines
    # ngspice requires TSTEP > 0; default to 1/1000 of TSTOP.
    assert ".tran 5e-06 5m" in lines
    assert ".meas tran VOUT_MAX MAX V(out)" in lines
    assert ".meas tran VOUT_MIN MIN V(out)" in lines
    assert lines[-1] == ".end"


def test_rc_highpass_emits_both_tran_and_ac() -> None:
    ir = load_ir(EXAMPLES_DIR / "rc_highpass.ir.json")
    text = render_netlist(ir).text
    lines = _strip_blank_lines(text)
    assert ".tran 2e-05 20m" in lines
    assert ".ac dec 20 10k" in lines


# --- component formatting ------------------------------------------------


def test_voltage_source_value_is_preserved_verbatim() -> None:
    """Rich SPICE expressions like SINE(...) and DC n must survive."""
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    text = render_netlist(ir).text
    assert "SINE(0 1 1k)" in text


def test_resistor_with_no_value_renders_without_trailing_token() -> None:
    ir = CircuitIR(
        schemaVersion="0.1",
        name="test_no_value_resistor",
        topology="rc_lowpass",
        nodes=["in", "out", "0"],
        components=[
            Component(
                id="Vin",
                kind=ComponentKind.VOLTAGE_SOURCE,
                spicePrefix="V",
                nodes=["in", "0"],
                value="DC 1",
            ),
            Component(
                id="R1",
                kind=ComponentKind.RESISTOR,
                spicePrefix="R",
                nodes=["in", "out"],
                value="1k",
            ),
            Component(
                id="C1",
                kind=ComponentKind.CAPACITOR,
                spicePrefix="C",
                nodes=["out", "0"],
                value="100n",
            ),
        ],
        analysis=[Analysis(kind=AnalysisKind.OP)],
    )
    text = render_netlist(ir).text
    assert "R1 in out 1k" in text
    assert "C1 out 0 100n" in text


# --- analysis formatting -------------------------------------------------


def test_tran_with_explicit_start_and_step_uses_three_arg_form() -> None:
    ir = CircuitIR(
        schemaVersion="0.1",
        name="test_tran_step",
        topology="rc_lowpass",
        nodes=["in", "out", "0"],
        components=[
            Component(
                id="Vin",
                kind=ComponentKind.VOLTAGE_SOURCE,
                spicePrefix="V",
                nodes=["in", "0"],
                value="DC 1",
            ),
            Component(
                id="R1",
                kind=ComponentKind.RESISTOR,
                spicePrefix="R",
                nodes=["in", "out"],
                value="1k",
            ),
            Component(
                id="C1",
                kind=ComponentKind.CAPACITOR,
                spicePrefix="C",
                nodes=["out", "0"],
                value="100n",
            ),
        ],
        analysis=[
            Analysis(kind=AnalysisKind.TRAN, startTime="1m", stopTime="10m", stepTime="0.1m")
        ],
    )
    text = render_netlist(ir).text
    assert ".tran 0.1m 10m 1m" in text


def test_tran_without_start_defaults_to_zero() -> None:
    ir = CircuitIR(
        schemaVersion="0.1",
        name="test_tran_default_start",
        topology="rc_lowpass",
        nodes=["in", "out", "0"],
        components=[
            Component(
                id="Vin",
                kind=ComponentKind.VOLTAGE_SOURCE,
                spicePrefix="V",
                nodes=["in", "0"],
                value="DC 1",
            ),
            Component(
                id="R1",
                kind=ComponentKind.RESISTOR,
                spicePrefix="R",
                nodes=["in", "out"],
                value="1k",
            ),
            Component(
                id="C1",
                kind=ComponentKind.CAPACITOR,
                spicePrefix="C",
                nodes=["out", "0"],
                value="100n",
            ),
        ],
        analysis=[Analysis(kind=AnalysisKind.TRAN, stopTime="5m")],
    )
    text = render_netlist(ir).text
    assert ".tran 5e-06 5m" in text


def test_op_emits_dot_op_directive() -> None:
    ir = load_ir(EXAMPLES_DIR / "voltage_divider.ir.json")
    text = render_netlist(ir).text
    assert ".op" in text


def test_ac_includes_points_per_decade_and_stop_freq() -> None:
    ir = CircuitIR(
        schemaVersion="0.1",
        name="test_ac",
        topology="rc_lowpass",
        nodes=["in", "out", "0"],
        components=[
            Component(
                id="Vin",
                kind=ComponentKind.VOLTAGE_SOURCE,
                spicePrefix="V",
                nodes=["in", "0"],
                value="AC 1",
            ),
            Component(
                id="R1",
                kind=ComponentKind.RESISTOR,
                spicePrefix="R",
                nodes=["in", "out"],
                value="1k",
            ),
            Component(
                id="C1",
                kind=ComponentKind.CAPACITOR,
                spicePrefix="C",
                nodes=["out", "0"],
                value="100n",
            ),
        ],
        analysis=[Analysis(kind=AnalysisKind.AC, stopFreq="1Meg", pointsPerDecade=20)],
    )
    text = render_netlist(ir).text
    assert ".ac dec 20 1Meg" in text


def test_dc_emits_sweep_tokens() -> None:
    ir = CircuitIR(
        schemaVersion="0.1",
        name="test_dc",
        topology="rc_lowpass",
        nodes=["in", "out", "0"],
        components=[
            Component(
                id="Vin",
                kind=ComponentKind.VOLTAGE_SOURCE,
                spicePrefix="V",
                nodes=["in", "0"],
                value="DC 0",
            ),
            Component(
                id="R1",
                kind=ComponentKind.RESISTOR,
                spicePrefix="R",
                nodes=["in", "out"],
                value="1k",
            ),
            Component(
                id="C1",
                kind=ComponentKind.CAPACITOR,
                spicePrefix="C",
                nodes=["out", "0"],
                value="100n",
            ),
        ],
        analysis=[
            Analysis(
                kind=AnalysisKind.DC,
                sweepVariable="Vin",
                sweepStart="0",
                sweepStop="5",
                sweepStep="0.1",
            )
        ],
    )
    text = render_netlist(ir).text
    assert ".dc Vin 0 5 0.1" in text


# --- measurement formatting ---------------------------------------------


def test_meas_emits_all_measurements() -> None:
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    text = render_netlist(ir).text
    assert ".meas tran VOUT_MAX MAX V(out)" in text
    assert ".meas tran VOUT_MIN MIN V(out)" in text


def test_meas_block_is_absent_when_no_measurements() -> None:
    ir = load_ir(EXAMPLES_DIR / "voltage_divider.ir.json")
    # Voltage divider has 1 measurement, so trim it for this test.
    object.__setattr__(ir, "measurements", [])
    text = render_netlist(ir).text
    assert ".meas" not in text


# --- directive safety ----------------------------------------------------


def test_include_directive_is_rejected_by_default() -> None:
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    ir.directives.append(".include /etc/passwd")
    with pytest.raises(NetlistError) as excinfo:
        render_netlist(ir)
    assert excinfo.value.code == "DIR_UNSUPPORTED"
    assert ".include" in str(excinfo.value)
    assert "/etc/passwd" not in str(excinfo.value) or "directive" in str(excinfo.value)


def test_lib_directive_is_rejected_by_default() -> None:
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    ir.directives.append(".lib /models/foo.lib")
    with pytest.raises(NetlistError) as excinfo:
        render_netlist(ir)
    assert excinfo.value.code == "DIR_UNSUPPORTED"
    assert ".lib" in str(excinfo.value)


def test_end_directive_is_never_in_directives_allowlist() -> None:
    """``.end`` belongs to the file structure, not the IR. The IR's
    allowlist must not include it, and the netlist generator appends
    its own ``.end`` exactly once.
    """
    from ltagent.ir import DIRECTIVE_ALLOWLIST as IR_ALLOWLIST
    from ltagent.netlist import DIRECTIVE_ALLOWLIST as NL_ALLOWLIST

    assert ".end" not in IR_ALLOWLIST
    assert ".end" not in NL_ALLOWLIST

    # Standard example: no .end duplication, exactly one .end at the end.
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    text = render_netlist(ir).text
    assert text.count(".end") == 1
    assert text.rstrip().endswith(".end")


def test_allowed_directive_passes_through() -> None:
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    ir.directives.append(".options reltol=0.001")
    text = render_netlist(ir).text
    assert ".options reltol=0.001" in text


def test_allow_unknown_directives_drops_rejected() -> None:
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    ir.directives.append(".include /etc/passwd")
    ir.directives.append(".options reltol=0.001")
    result = render_netlist(ir, allow_unknown_directives=True)
    assert result.rejected_directives == [".include /etc/passwd"]
    assert ".include" not in result.text
    assert ".options reltol=0.001" in result.text


def test_allowlist_matches_doc_string() -> None:
    """Sanity: the allowlist must be a non-empty frozenset of strings
    starting with a dot."""
    assert isinstance(DIRECTIVE_ALLOWLIST, frozenset)
    assert DIRECTIVE_ALLOWLIST
    for entry in DIRECTIVE_ALLOWLIST:
        assert entry.startswith(".")
    # Path-bearing directives must be excluded (plan section 18.1).
    assert ".include" not in DIRECTIVE_ALLOWLIST
    assert ".lib" not in DIRECTIVE_ALLOWLIST


# --- write_netlist ------------------------------------------------------


def test_write_netlist_creates_file(tmp_path: Path) -> None:
    ir = load_ir(EXAMPLES_DIR / "voltage_divider.ir.json")
    out = tmp_path / "out.cir"
    result = write_netlist(ir, out)
    assert out.is_file()
    assert out.read_text(encoding="utf-8") == result.text


def test_write_netlist_creates_parent_dirs(tmp_path: Path) -> None:
    ir = load_ir(EXAMPLES_DIR / "voltage_divider.ir.json")
    out = tmp_path / "deep" / "nested" / "out.cir"
    result = write_netlist(ir, out)
    assert out.is_file()
    assert out.read_text(encoding="utf-8") == result.text


def test_write_netlist_rejects_unsafe_directive(tmp_path: Path) -> None:
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    ir.directives.append(".include /etc/passwd")
    out = tmp_path / "out.cir"
    with pytest.raises(NetlistError):
        write_netlist(ir, out)
    assert not out.exists()


# --- NetlistResult shape ------------------------------------------------


def test_result_counters_match_rendered_text() -> None:
    ir = load_ir(EXAMPLES_DIR / "rc_lowpass.ir.json")
    result = render_netlist(ir)
    assert isinstance(result, NetlistResult)
    assert result.component_count == 3
    assert result.analysis_count == 1
    assert result.measurement_count == 2
    assert result.line_count == len(_strip_blank_lines(result.text))
    assert result.header[0].startswith(f"* Generated by {GENERATOR_NAME}")


# --- error code surface -------------------------------------------------


def test_netlist_error_carries_code_detail_data() -> None:
    exc = NetlistError("FOO", "bar", data={"x": 1})
    assert exc.code == "FOO"
    assert exc.detail == "bar"
    assert exc.data == {"x": 1}
    assert "FOO" in str(exc)
