"""Tests for :mod:`ltagent.math_core.standard_values`.

The standard-values module is the math core's preferred-value lookup
table. The tests pin down the IEC 60063 series sizes and the
nearest-value selection algorithm so a refactor cannot accidentally
loosen the tolerance.
"""

from __future__ import annotations

import math

import pytest

from ltagent.math_core.standard_values import (
    SUPPORTED_SERIES,
    StandardValueSelection,
    calculate_error_percent,
    decade_of,
    nearest_standard_value,
    series_values,
)

# ---------------------------------------------------------------------------
# Series tables
# ---------------------------------------------------------------------------


def test_supported_series_includes_e6_e12_e24() -> None:
    """The MVP series set is non-negotiable per the live-editing plan."""
    assert {"E6", "E12", "E24"} <= SUPPORTED_SERIES


def test_e6_has_six_values_per_decade() -> None:
    ladder = series_values("E6")
    decade_values = [v for v in ladder if 1 <= v < 10]
    assert len(decade_values) == 6
    # The classic E6 mantissas.
    expected = {1.0, 1.5, 2.2, 3.3, 4.7, 6.8}
    assert {round(v, 6) for v in decade_values} == expected


def test_e12_has_twelve_values_per_decade() -> None:
    ladder = series_values("E12")
    decade_values = [v for v in ladder if 1 <= v < 10]
    assert len(decade_values) == 12
    expected = {1.0, 1.2, 1.5, 1.8, 2.2, 2.7, 3.3, 3.9, 4.7, 5.6, 6.8, 8.2}
    assert {round(v, 6) for v in decade_values} == expected


def test_e24_has_twenty_four_values_per_decade() -> None:
    ladder = series_values("E24")
    decade_values = [v for v in ladder if 1 <= v < 10]
    assert len(decade_values) == 24
    expected = {
        1.0, 1.1, 1.2, 1.3, 1.5, 1.6, 1.8, 2.0, 2.2, 2.4, 2.7, 3.0,
        3.3, 3.6, 3.9, 4.3, 4.7, 5.1, 5.6, 6.2, 6.8, 7.5, 8.2, 9.1,
    }
    assert {round(v, 6) for v in decade_values} == expected


def test_series_values_spans_a_wide_range() -> None:
    """The ladder covers at least 1e-12 .. 1e12 so any engineering
    value can be matched without overflow."""
    ladder = series_values("E24")
    assert min(ladder) <= 1e-12
    assert max(ladder) >= 1e12


def test_series_values_are_sorted() -> None:
    ladder = series_values("E24")
    assert ladder == tuple(sorted(ladder))


def test_series_values_deduplicates() -> None:
    """E48 and E96 are generated by exponentiation; duplicates must
    be removed (e.g. 1.0 repeats across the integer-decade boundary)."""
    ladder = series_values("E96")
    assert len(ladder) == len(set(ladder))


def test_unsupported_series_raises() -> None:
    with pytest.raises(ValueError, match="unsupported series"):
        series_values("E1")


# ---------------------------------------------------------------------------
# calculate_error_percent
# ---------------------------------------------------------------------------


def test_calculate_error_percent_zero_ideal() -> None:
    """A zero ideal is handled gracefully (no division by zero)."""
    assert calculate_error_percent(0, 0) == 0.0
    # Non-zero selected is reported as percent of one (i.e. magnitude % 1).
    assert calculate_error_percent(0, 1) == 100.0
    assert calculate_error_percent(0, -1) == 100.0


def test_calculate_error_percent_signs() -> None:
    """``(selected - ideal) / ideal * 100`` — positive when selected
    is larger than the ideal."""
    assert calculate_error_percent(100, 110) == pytest.approx(10.0)
    assert calculate_error_percent(100, 90) == pytest.approx(-10.0)


def test_calculate_error_percent_rejects_nan() -> None:
    with pytest.raises(ValueError, match="finite"):
        calculate_error_percent(math.nan, 100.0)
    with pytest.raises(ValueError, match="finite"):
        calculate_error_percent(100.0, math.inf)


def test_calculate_error_percent_rejects_none() -> None:
    with pytest.raises(ValueError, match="finite"):
        calculate_error_percent(None, 100.0)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# nearest_standard_value
# ---------------------------------------------------------------------------


def test_nearest_standard_value_e24_picks_1p6k_for_1591() -> None:
    """Spec: 1kHz RC low-pass → ideal 1591.55 Ω → E24 picks 1.6kΩ."""
    sel = nearest_standard_value(1_591.55, "E24")
    assert isinstance(sel, StandardValueSelection)
    assert sel.series == "E24"
    assert sel.selected == pytest.approx(1_600.0)
    assert sel.error_percent == pytest.approx(0.528, rel=1e-2)


def test_nearest_standard_value_e12_picks_1p5k_for_1591() -> None:
    """E12's nearest is 1.5kΩ (no 1.6kΩ in the E12 ladder)."""
    sel = nearest_standard_value(1_591.55, "E12")
    assert sel.selected == pytest.approx(1_500.0)
    # Signed error: (1500 - 1591.55) / 1591.55 * 100 ≈ -5.7 %
    assert sel.error_percent == pytest.approx(-5.74, rel=1e-2)


def test_nearest_standard_value_e6_picks_1p5k_for_1591() -> None:
    """E6 has only 1.5 / 2.2 → 1.5k is closest."""
    sel = nearest_standard_value(1_591.55, "E6")
    assert sel.selected == pytest.approx(1_500.0)


def test_nearest_standard_value_exact_match() -> None:
    """A value that already exists in the series is returned unchanged."""
    sel = nearest_standard_value(1_000.0, "E24")
    assert sel.selected == 1_000.0
    assert sel.error_percent == 0.0


def test_nearest_standard_value_tie_breaks_larger() -> None:
    """A 50 Ω ideal sits exactly between 47 Ω and 51 Ω in E24. The
    tie-break must pick the *larger* value (safer default)."""
    sel = nearest_standard_value(50.0, "E24")
    # 47 and 51 are equidistant in percent terms; expect 51.
    assert sel.selected >= 50.0


def test_nearest_standard_value_handles_very_small() -> None:
    sel = nearest_standard_value(1e-9, "E24")
    assert sel.selected > 0
    assert sel.selected <= 1e-9 * 1.5


def test_nearest_standard_value_handles_very_large() -> None:
    sel = nearest_standard_value(1e9, "E24")
    assert sel.selected >= 1e9
    assert sel.selected <= 1e9 * 1.5


def test_nearest_standard_value_rejects_zero() -> None:
    with pytest.raises(ValueError, match="positive"):
        nearest_standard_value(0.0, "E24")


def test_nearest_standard_value_rejects_negative() -> None:
    with pytest.raises(ValueError, match="positive"):
        nearest_standard_value(-1_000.0, "E24")


def test_nearest_standard_value_rejects_unknown_series() -> None:
    with pytest.raises(ValueError, match="unsupported series"):
        nearest_standard_value(1_000.0, "E1")


def test_standard_value_selection_to_dict() -> None:
    sel = nearest_standard_value(1_591.55, "E24")
    payload = sel.to_dict()
    assert payload["ideal"] == pytest.approx(1_591.55)
    assert payload["series"] == "E24"
    assert payload["selected"] == pytest.approx(1_600.0)
    assert "errorPercent" in payload


# ---------------------------------------------------------------------------
# decade_of
# ---------------------------------------------------------------------------


def test_decade_of_basic() -> None:
    assert decade_of(1.0) == 0
    assert decade_of(9.99) == 0
    assert decade_of(10.0) == 1
    assert decade_of(1_591.55) == 3
    assert decade_of(1e6) == 6
    assert decade_of(1e-9) == -9


def test_decade_of_rejects_non_positive() -> None:
    with pytest.raises(ValueError, match="positive"):
        decade_of(0.0)
    with pytest.raises(ValueError, match="positive"):
        decade_of(-1.0)
