"""Tiny8 Verilog-2001 templates (Phase 12, v1).

The generator (``ltagent.digital_generator``) composes these
templates with the ``DesignIR`` to produce the project's RTL
files. **No free-form HDL is ever produced.** Every Verilog
character on disk came from one of these strings + a validated
``DesignIR`` field.

Style conventions (carried from docs/digital/plan-tiny8-agent.md
§8.1 and the lowRISC Verilog style guide):

* Verilog-2001 only. No SystemVerilog.
* Module names: ``tiny8_<block>``.
* Signal names: descriptive ``snake_case``.
* Clock/reset ports first: ``clk``, ``rst``.
* Sequential logic: nonblocking assignment.
* Combinational logic: ``always @*`` with blocking.
* No inferred latches, no unsized constants in critical datapath.
* Every file has the do-not-edit header at the top.

Each module is exposed as a Python string constant. The
generator uses ``str.format()`` (with explicit ``{...}`` keys
for the IR-driven values) to render the file. **No
``str.format()`` is used on the body of the Verilog itself**;
the templates use sentinel markers (``%(name)s``-style would be
insecure; we use plain ``str.replace`` on stable tokens in the
generator).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# File header
# ---------------------------------------------------------------------------

GENERATED_HEADER: str = """\
// -----------------------------------------------------------------------------
// THIS FILE IS GENERATED BY ltspice-ai-agent (Phase 12, Tiny8 CPU).
// DO NOT EDIT BY HAND. Regenerate via `ltagent digital create`.
// Source: design.ir.json (Design IR v0.1, kind=tiny8_cpu)
// -----------------------------------------------------------------------------
"""

# ---------------------------------------------------------------------------
# tiny8_alu
# ---------------------------------------------------------------------------

# A 4-bit ALU opcode is internal to this module. The 16-bit ISA
# opcode is decoded by ``tiny8_control`` into these internal
# signals. Keeping a tiny private opcode space here makes the
# ALU self-contained and easy to test in isolation.
#
# Local ALU opcodes (must match ``tiny8_control``):
#   0 = PASS (operand -> acc, no arithmetic)
#   1 = ADD
#   2 = SUB
#   3 = AND
#   4 = OR
#   5 = XOR

ALU_OP_PASS: int = 0
ALU_OP_ADD: int = 1
ALU_OP_SUB: int = 2
ALU_OP_AND: int = 3
ALU_OP_OR: int = 4
ALU_OP_XOR: int = 5

TINY8_ALU_V: str = """\
__HEADER__module tiny8_alu (
    input  wire [3:0] op,
    input  wire [7:0] acc,
    input  wire [7:0] operand,
    output reg  [7:0] result,
    output wire       zero
);
    // Combinational: select operation, compute result, drive zero flag.
    always @* begin
        case (op)
            4'd0: result = acc;            // PASS (LDI / LDA / STA / OUT / IN)
            4'd1: result = acc + operand;  // ADD
            4'd2: result = acc - operand;  // SUB
            4'd3: result = acc & operand;  // AND
            4'd4: result = acc | operand;  // OR
            4'd5: result = acc ^ operand;  // XOR
            default: result = 8'h00;
        endcase
    end

    assign zero = (result == 8'h00);
endmodule
"""


# ---------------------------------------------------------------------------
# tiny8_control
# ---------------------------------------------------------------------------

# Internal control signals driven by the instruction opcode. The
# ALU op is a 4-bit one-hot-ish field; the rest are 1-bit enables.
#
# control_out layout (output reg [10:0]):
#   [10]   halted_next (sticky once set)
#   [9]    pc_load    (1 = pc <= operand for JMP/JZ/JNZ taken)
#   [8]    pc_inc     (1 = pc <= pc + 1, default)
#   [7]    acc_we     (1 = write acc from alu result)
#   [6]    ram_we     (1 = write ram[operand] = acc)
#   [5:2]  alu_op     (4-bit ALU opcode; PASS=0, ADD=1, ...)
#   [1]    out_valid  (1 = drive out_port/out_data this cycle)
#   [0]    ram_re     (1 = operand fed to ram addr this cycle)

TINY8_CONTROL_V: str = """\
__HEADER__module tiny8_control (
    input  wire [15:0] instr,
    input  wire        zero_flag,
    output reg  [10:0] ctl,
    output reg         illegal
);
    // Decode the 4-bit ISA opcode and the 8-bit operand.
    wire [3:0] opcode = instr[15:12];
    wire [7:0] operand = instr[7:0];

    // Default: pc++ and no side-effects.
    always @* begin
        ctl     = 11'b0_0_0_0_0000_0_0;
        illegal = 1'b0;
        ctl[8]  = 1'b1; // pc_inc by default

        case (opcode)
            4'h0: begin // NOP
                // nothing extra
            end
            4'h1: begin // LDI imm
                ctl[7]    = 1'b1; // acc_we
                ctl[5:2]  = 4'd0; // ALU PASS
            end
            4'h2: begin // LDA addr
                ctl[7]    = 1'b1; // acc_we
                ctl[0]    = 1'b1; // ram_re
                ctl[5:2]  = 4'd0; // ALU PASS
            end
            4'h3: begin // STA addr
                ctl[6]    = 1'b1; // ram_we
            end
            4'h4: begin // ADD addr
                ctl[7]    = 1'b1;
                ctl[0]    = 1'b1;
                ctl[5:2]  = 4'd1; // ALU ADD
            end
            4'h5: begin // SUB addr
                ctl[7]    = 1'b1;
                ctl[0]    = 1'b1;
                ctl[5:2]  = 4'd2; // ALU SUB
            end
            4'h6: begin // AND addr
                ctl[7]    = 1'b1;
                ctl[0]    = 1'b1;
                ctl[5:2]  = 4'd3; // ALU AND
            end
            4'h7: begin // OR addr
                ctl[7]    = 1'b1;
                ctl[0]    = 1'b1;
                ctl[5:2]  = 4'd4; // ALU OR
            end
            4'h8: begin // XOR addr
                ctl[7]    = 1'b1;
                ctl[0]    = 1'b1;
                ctl[5:2]  = 4'd5; // ALU XOR
            end
            4'h9: begin // JMP addr
                ctl[9]    = 1'b1; // pc_load
                ctl[8]    = 1'b0; // override pc_inc
            end
            4'hA: begin // JZ addr
                if (zero_flag) begin
                    ctl[9] = 1'b1; // pc_load
                    ctl[8] = 1'b0;
                end
            end
            4'hB: begin // JNZ addr
                if (!zero_flag) begin
                    ctl[9] = 1'b1;
                    ctl[8] = 1'b0;
                end
            end
            4'hC: begin // OUT port
                ctl[1]    = 1'b1; // out_valid
            end
            4'hD: begin // IN port
                ctl[7]    = 1'b1; // acc_we (from in_data; tiny8_cpu wires this)
                ctl[5:2]  = 4'd0; // ALU PASS
            end
            4'hE: begin // reserved
                illegal   = 1'b1;
            end
            4'hF: begin // HALT
                ctl[10]   = 1'b1; // halted_next
                ctl[8]    = 1'b0; // do not advance pc
            end
            default: begin
                illegal   = 1'b1;
            end
        endcase
    end
endmodule
"""


# ---------------------------------------------------------------------------
# tiny8_rom
# ---------------------------------------------------------------------------

# The .mem file is loaded with $readmemh at time 0. The default
# demo program is empty (all zeros -> NOP); the generator writes
# the real program into the .mem file.

TINY8_ROM_V: str = """\
__HEADER__module tiny8_rom #(
    parameter ADDR_WIDTH = 8,
    parameter DATA_WIDTH = 16,
    parameter MEM_FILE   = "demo.mem"
) (
    input  wire                    clk,
    input  wire [ADDR_WIDTH-1:0]   addr,
    output reg  [DATA_WIDTH-1:0]   data
);
    // 256 x 16-bit program memory. Initialised from MEM_FILE
    // (Icarus + Yosys both support $readmemh).
    reg [DATA_WIDTH-1:0] mem [0:(1<<ADDR_WIDTH)-1];

    initial begin
        $readmemh(MEM_FILE, mem);
    end

    always @(posedge clk) begin
        data <= mem[addr];
    end
endmodule
"""


# ---------------------------------------------------------------------------
# tiny8_ram
# ---------------------------------------------------------------------------

TINY8_RAM_V: str = """\
__HEADER__module tiny8_ram #(
    parameter ADDR_WIDTH = 8,
    parameter DATA_WIDTH = 8
) (
    input  wire                    clk,
    input  wire                    we,
    input  wire [ADDR_WIDTH-1:0]   addr,
    input  wire [DATA_WIDTH-1:0]   wdata,
    output reg  [DATA_WIDTH-1:0]   rdata
);
    // 256-byte data memory, synchronous read + write.
    reg [DATA_WIDTH-1:0] mem [0:(1<<ADDR_WIDTH)-1];

    always @(posedge clk) begin
        if (we) begin
            mem[addr] <= wdata;
            rdata    <= wdata;
        end else begin
            rdata    <= mem[addr];
        end
    end
endmodule
"""


# ---------------------------------------------------------------------------
# tiny8_cpu
# ---------------------------------------------------------------------------

TINY8_CPU_V: str = """\
__HEADER__module tiny8_cpu #(
    parameter ADDR_WIDTH   = 8,
    parameter DATA_WIDTH   = 8,
    parameter INSTR_WIDTH  = 16
) (
    input  wire                    clk,
    input  wire                    rst,

    // External memory busses. The wrapper (tiny8_top) wires these
    // to the ROM and RAM instances.
    output wire [ADDR_WIDTH-1:0]   rom_addr,
    input  wire [INSTR_WIDTH-1:0]  rom_data,

    output wire                    ram_we,
    output wire [ADDR_WIDTH-1:0]   ram_addr,
    output wire [DATA_WIDTH-1:0]   ram_wdata,
    input  wire [DATA_WIDTH-1:0]   ram_rdata,

    // IO ports (v1: just an OUT strobe + data)
    output wire                    out_valid,
    output wire [DATA_WIDTH-1:0]   out_port,
    output wire [DATA_WIDTH-1:0]   out_data,

    // Status visible to the wrapper and the testbench.
    output wire [ADDR_WIDTH-1:0]   pc_out,
    output wire [DATA_WIDTH-1:0]   acc_out,
    output wire                    halted_out
);
    // Program counter.
    reg [ADDR_WIDTH-1:0] pc;
    reg [ADDR_WIDTH-1:0] next_pc;

    // Accumulator + zero flag.
    reg [DATA_WIDTH-1:0] acc;
    reg                  zero_flag;

    // Sticky halt.
    reg                  halted;

    // Current instruction, captured at fetch.
    reg [INSTR_WIDTH-1:0] instr;

    // ALU + control.
    wire [10:0] ctl;
    wire        illegal;
    wire [7:0]  alu_result;
    wire        alu_zero;

    tiny8_control u_control (
        .instr     (instr),
        .zero_flag (zero_flag),
        .ctl       (ctl),
        .illegal   (illegal)
    );

    tiny8_alu u_alu (
        .op      (ctl[5:2]),
        .acc     (acc),
        .operand (ram_rdata),
        .result  (alu_result),
        .zero    (alu_zero)
    );

    // pc update
    always @* begin
        if (ctl[9])
            next_pc = instr[ADDR_WIDTH-1:0];
        else if (ctl[8])
            next_pc = pc + 1'b1;
        else
            next_pc = pc;
    end

    // main state register
    always @(posedge clk) begin
        if (rst) begin
            pc        <= {ADDR_WIDTH{1'b0}};
            acc       <= {DATA_WIDTH{1'b0}};
            zero_flag <= 1'b1;
            halted    <= 1'b0;
            instr     <= {INSTR_WIDTH{1'b0}};
        end else if (!halted) begin
            // Fetch
            instr <= rom_data;
            // pc
            pc    <= next_pc;
            // acc
            if (ctl[7])
                acc <= alu_result;
            // zero_flag updates when acc is written or after ALU pass.
            if (ctl[7])
                zero_flag <= alu_zero;
            // halt
            if (ctl[10])
                halted <= 1'b1;
        end
        // Illegal opcode: leave state alone for visibility; the
        // testbench checks ``illegal`` and fails the run.
    end

    assign rom_addr = pc;
    assign ram_we   = ctl[6];
    assign ram_addr = instr[ADDR_WIDTH-1:0];
    assign ram_wdata= acc;
    assign out_valid= ctl[1];
    assign out_port = instr[DATA_WIDTH-1:0];
    assign out_data = acc;
    assign pc_out   = pc;
    assign acc_out  = acc;
    assign halted_out = halted;
endmodule
"""


# ---------------------------------------------------------------------------
# tiny8_top
# ---------------------------------------------------------------------------

TINY8_TOP_V: str = """\
__HEADER__module tiny8_top #(
    parameter ADDR_WIDTH  = 8,
    parameter DATA_WIDTH  = 8,
    parameter INSTR_WIDTH = 16
) (
    input  wire                    clk,
    input  wire                    rst,

    output wire                    out_valid,
    output wire [DATA_WIDTH-1:0]   out_port,
    output wire [DATA_WIDTH-1:0]   out_data,

    output wire [ADDR_WIDTH-1:0]   pc_out,
    output wire [DATA_WIDTH-1:0]   acc_out,
    output wire                    halted_out
);
    wire [ADDR_WIDTH-1:0] rom_addr;
    wire [INSTR_WIDTH-1:0] rom_data;

    wire        ram_we;
    wire [ADDR_WIDTH-1:0] ram_addr;
    wire [DATA_WIDTH-1:0] ram_wdata;
    wire [DATA_WIDTH-1:0] ram_rdata;

    tiny8_rom #(
        .ADDR_WIDTH (ADDR_WIDTH),
        .DATA_WIDTH (INSTR_WIDTH)
    ) u_rom (
        .clk  (clk),
        .addr (rom_addr),
        .data (rom_data)
    );

    tiny8_ram #(
        .ADDR_WIDTH (ADDR_WIDTH),
        .DATA_WIDTH (DATA_WIDTH)
    ) u_ram (
        .clk   (clk),
        .we    (ram_we),
        .addr  (ram_addr),
        .wdata (ram_wdata),
        .rdata (ram_rdata)
    );

    tiny8_cpu #(
        .ADDR_WIDTH  (ADDR_WIDTH),
        .DATA_WIDTH  (DATA_WIDTH),
        .INSTR_WIDTH (INSTR_WIDTH)
    ) u_cpu (
        .clk       (clk),
        .rst       (rst),
        .rom_addr  (rom_addr),
        .rom_data  (rom_data),
        .ram_we    (ram_we),
        .ram_addr  (ram_addr),
        .ram_wdata (ram_wdata),
        .ram_rdata (ram_rdata),
        .out_valid (out_valid),
        .out_port  (out_port),
        .out_data  (out_data),
        .pc_out    (pc_out),
        .acc_out   (acc_out),
        .halted_out(halted_out)
    );
endmodule
"""


# ---------------------------------------------------------------------------
# tb_tiny8_top
# ---------------------------------------------------------------------------

# The testbench is driven by the ``program.source`` assembler
# output. It loads the .mem at time 0, asserts reset, waits for
# halt, then checks the verification contract.
#
# The testbench expects the following to be substituted by the
# generator:
#   ROM_FILE        path to the .mem file (e.g. "demo.mem")
#   MAX_CYCLES      expectedHaltCyclesMax (decimal integer)
#   EXP_HALTED      "1'b1" (always true for v1)
#   EXP_ACC         "8'h2a" (default: 42 = 0x2a)
#   EXP_MEM_CHECKS  list of "if (ram[16] !== 8'h14) $fatal(1); ..." etc.

TINY8_TB_V: str = """\
__HEADER__`timescale 1ns/1ps

module tb_tiny8_top;
    reg         clk;
    reg         rst;
    wire        out_valid;
    wire [7:0]  out_port;
    wire [7:0]  out_data;
    wire [7:0]  pc;
    wire [7:0]  acc;
    wire        halted;

    // Expose the DUT's RAM for direct verification.
    reg [7:0]  ram_mem [0:255];

    integer    cycles;
    reg        failed;

    tiny8_top u_dut (
        .clk       (clk),
        .rst       (rst),
        .out_valid (out_valid),
        .out_port  (out_port),
        .out_data  (out_data),
        .pc_out    (pc),
        .acc_out   (acc),
        .halted_out(halted)
    );

    // 100 MHz-ish clock: 10 ns period.
    initial clk = 1'b0;
    always #5 clk = ~clk;

    // Capture RAM writes for verification. The DUT's RAM is internal
    // to tiny8_top, so we mirror the same protocol from a testbench
    // point of view by snooping the bus here.
    //
    // The testbench drives the same write events by peeking at the
    // CPU's bus through a hierarchical reference. Icarus and Verilator
    // both support this.
    always @(posedge clk) begin
        if (!rst && u_dut.u_cpu.ram_we) begin
            ram_mem[u_dut.u_cpu.ram_addr] <= u_dut.u_cpu.ram_wdata;
        end
    end

    initial begin
        failed = 1'b0;
        // reset
        rst    = 1'b1;
        cycles = 0;
        ram_mem = '{256{8'h00}};
        #20;
        rst = 1'b0;
    end

    // cycle counter + halt timeout
    always @(posedge clk) begin
        if (!rst) begin
            cycles <= cycles + 1;
            if (halted) begin
                $display("TB_PASS halted at cycle %0d acc=%h", cycles, acc);
                // Verification contract
                if (__EXP_HALTED__) begin
                    $display("TB_CHECK halted=1 ok");
                end else begin
                    $display("TB_FAIL halted mismatch");
                    failed = 1'b1;
                end
                if (__EXP_ACC_EN__) begin
                    if (acc !== __EXP_ACC__) begin
                        $display("TB_FAIL acc expected __EXP_ACC__ got %h", acc);
                        failed = 1'b1;
                    end else begin
                        $display("TB_CHECK acc=__EXP_ACC__ ok");
                    end
                end
__EXP_MEM_CHECKS__
                if (failed) begin
                    $display("TB_FAIL overall");
                    $fatal(1);
                end else begin
                    $display("TB_PASS overall");
                    $finish;
                end
            end
            if (cycles > __MAX_CYCLES__) begin
                $display("TB_FAIL timeout after %0d cycles (halted=%b acc=%h)",
                         cycles, halted, acc);
                $fatal(1);
            end
        end
    end
endmodule
"""


# ---------------------------------------------------------------------------
# Tiny8 SoC top (reserved, not generated in v1)
# ---------------------------------------------------------------------------

# Tiny8 SoC wraps the CPU with a memory-mapped IO bus. v1 only
# ships ``tiny8_cpu``; this template is here so the generator can
# later emit it without changes to the template system. It is not
# referenced by any code path today.
TINY8_SOC_TOP_V: str = """\
__HEADER__// Reserved for v1.1: Tiny8 SoC with memory-mapped IO. Not
// generated in v1. See docs/digital/plan-tiny8-agent.md §12 (Phase F).
module tiny8_soc_top (
    input  wire clk,
    input  wire rst,
    output wire halted
);
    // Placeholder. The SoC is a wrapper that adds an address-decode
    // stage and a memory-mapped IO block. v1 ships the bare CPU only.
    assign halted = 1'b0;
endmodule
"""


# ---------------------------------------------------------------------------
# Mapping of file name -> (template body, IR-driven substitutions)
# ---------------------------------------------------------------------------

# The generator looks up a template by its relative path. The
# ``ir_substitutions`` callable receives the validated DesignIR
# and returns a dict used for ``str.format`` substitution. Keeping
# the substitution as a function (not a constant dict) means the
# IR can drive file content beyond simple width fields.

# Substitutions the generator always provides:
#   - ``header``: the do-not-edit banner.
#   - everything the IR-driven ``ir_subs`` adds.
