#!/usr/bin/env python3
"""Phase 10 build script: package the ltagent sidecar and inspect the
Tauri bundle config.

The script is intentionally a thin wrapper:

1. Build the ltagent sdist + wheel via ``python -m build``.
2. Stage the entry-point scripts as the sidecar binaries the
   Tauri shell expects (without actually cross-compiling
   here; the real bundling step is driven by ``tauri build``).
3. Print the Tauri bundle config so a release engineer can
   verify ``externalBin`` paths.

It is meant to be run from CI; the Tauri build itself is run
separately because it needs the GTK / WebKit / librsvg stack
that the Python core does not require.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DIST = REPO_ROOT / "dist"
SIDECAR_DIR = REPO_ROOT / "apps" / "desktop" / "sidecar"
TAURI_CONFIG = REPO_ROOT / "apps" / "desktop" / "src-tauri" / "tauri.conf.json"


def _stage_sidecar() -> list[Path]:
    """Document the ltagent entry-point scripts in the sidecar dir.

    The Tauri shell uses ``tauri.conf.json`` ``bundle.externalBin``
    to find the binaries. We do not know the host triple at
    runtime; the actual binary file is produced by
    ``pyinstaller`` (or equivalent) before ``tauri build`` runs.
    This stage writes a tiny stub script so a release engineer
    can see the intended entry points.
    """
    import importlib.metadata

    SIDECAR_DIR.mkdir(parents=True, exist_ok=True)
    try:
        eps = importlib.metadata.entry_points()
    except Exception as exc:  # pragma: no cover
        print(f"WARN: entry points unavailable: {exc}")
        return []

    targets = {
        "ltagent": "ltagent.cli:main",
        "ltagent-engine": "ltagent.engine_server:main",
        "ltagent-mcp": "ltagent.mcp_server:main",
    }
    discovered: dict[str, str] = {
        ep.name: ep.value for ep in eps.select(group="console_scripts") if ep.name in targets
    }
    staged: list[Path] = []
    for name, target in targets.items():
        module_path = target.split(":", 1)[0]
        dest = SIDECAR_DIR / name
        dest.write_text(
            "#!/usr/bin/env python3\n"
            "# Auto-generated by scripts/build_sidecar.py\n"
            "# Real sidecar: replace with the PyInstaller-frozen\n"
            "# binary before `tauri build`.\n"
            f"# Target: {target}\n"
            "import sys\n"
            f"from {module_path} import main\n"
            "if __name__ == '__main__':\n"
            "    sys.exit(main())\n"
        )
        dest.chmod(0o755)
        staged.append(dest)
        if name not in discovered:
            print(f"WARN: entry point {name} not declared in pyproject.toml")
    return staged


def _build_sdist_wheel() -> None:
    DIST.mkdir(exist_ok=True)
    subprocess.run(
        [sys.executable, "-m", "build", "--sdist", "--wheel", "--outdir", str(DIST)],
        cwd=REPO_ROOT,
        check=True,
    )


def _print_tauri_config() -> None:
    if not TAURI_CONFIG.is_file():
        print("WARN: tauri.conf.json not found; skipping inspection")
        return
    text = TAURI_CONFIG.read_text(encoding="utf-8")
    config = json.loads(text)
    external = config.get("bundle", {}).get("externalBin") or []
    print(
        json.dumps(
            {
                "productName": config.get("productName"),
                "version": config.get("version"),
                "identifier": config.get("identifier"),
                "externalBin": external,
                "targets": config.get("bundle", {}).get("targets"),
            },
            indent=2,
            sort_keys=True,
        )
    )


def main() -> int:
    _build_sdist_wheel()
    staged = _stage_sidecar()
    print(f"Staged {len(staged)} sidecar script(s) in {SIDECAR_DIR}")
    for path in staged:
        print(f"  - {path.relative_to(REPO_ROOT)}")
    print("Tauri config:")
    _print_tauri_config()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
