#!/usr/bin/env python3
# Auto-generated by scripts/build_sidecar.py
# Imports the installed entry point and delegates.
from ltagent import __version__ as _v
import sys
from ltagent.ltagent import main
if __name__ == '__main__':
    sys.exit(main())
